### ISSUE TITLE
XTM505

### ISSUE THREAD

**Issue by KosbIga** [amnemonic/wg_firebox#2]
Hello!
Testing on xtm505 11.7.5.B451172, dont work.
Generation keys - ok, veryfing -ok, when upload feauture key have - Code : 1001 Invalid License.
And test this on m200 11.11.2 -the same

**Comment by amnemonic** [comment]
Can you check/confirm if replacement of original `/etc/lickey.pem` on target device was successful?

**Comment by KosbIga** [comment]
I apologize. Everything worked after installing a clean VM with openssl. Apparently there is some kind of problem with openssl on my PC. Tested on the XTM520 and on the M200. The devices have also been updated to the latest versions for these models. I express my great gratitude, since the vendor has stopped supporting EOL devices. I shake hands with Amnemonic.

**Comment by amnemonic** [comment]
Happy to hear that! And indeed, if you just want to upgrade your appliance to latest version which will not accept this solution, you should be able to downgrade to version under 12.5.9 then patch and generate license which contain `LIVESECURITY` feature. This should allow to install latest version of os image.

**Comment by linkshahzad** [comment]
I need M5600 solution basic sec key, is it possible?
